[tools]
hk = "latest"
pkl = "latest"

[tasks.prebuild]
description = "Build generated assets"
run = "bun run prebuild"

[tasks.postlint]
description = "Add any changed files to the commit"
run = "git status && git add . && git commit --amend --no-edit"