/* Autogenerated file */
/* do not edit */
import type { HydratedFrontmatter } from "#/types";

export let recentMicroposts: Array<HydratedFrontmatter> = [
  {
    "title": "Link: Next.js Is Infuriating",
    "slug": "link-nextjs-is-infuriating",
    "path": "/2025/september/link-nextjs-is-infuriating",
    "date": 1756821323897,
    "status": "public",
    "type": "micropost",
    "tags": [
      "micropost",
      "Links"
    ],
    "month": "september",
    "year": 2025,
    "ogImage": "/og-images/link-nextjs-is-infuriating.png",
    "blueskyPostUri": "",
    "location": "Somewhere over the Atlantic between Edinburgh Scotland and Boston MA",
    "lastModified": 1756821742000
  },
  {
    "title": "Dependabot Hell",
    "slug": "dependabot-hell",
    "path": "/2025/august/dependabot-hell",
    "date": 1756314642129,
    "status": "public",
    "type": "micropost",
    "tags": [
      "micropost"
    ],
    "month": "august",
    "year": 2025,
    "ogImage": "/og-images/dependabot-hell.png",
    "blueskyPostUri": "",
    "location": "Boston, MA",
    "lastModified": 1756314841000
  },
  {
    "title": "Link: What the hell is going on right now?",
    "slug": "link-what-the-hell-is-going-on-right-now",
    "path": "/2025/august/link-what-the-hell-is-going-on-right-now",
    "date": 1755910704752,
    "status": "public",
    "type": "micropost",
    "tags": [
      "micropost",
      "Links"
    ],
    "month": "august",
    "year": 2025,
    "ogImage": "/og-images/link-what-the-hell-is-going-on-right-now.png",
    "blueskyPostUri": "",
    "location": "Boston, MA",
    "lastModified": 1755911334000
  },
  {
    "title": "Recipe: Horchata Protein Latte",
    "slug": "recipe-horchata-protein-latte",
    "path": "/2025/august/recipe-horchata-protein-latte",
    "date": 1754914452114,
    "status": "public",
    "type": "micropost",
    "tags": [
      "micropost",
      "recipe"
    ],
    "month": "august",
    "year": 2025,
    "ogImage": "/og-images/recipe-horchata-protein-latte.png",
    "blueskyPostUri": "",
    "location": "Boston, MA",
    "lastModified": 1755605056000
  },
  {
    "title": "Zombie Retros",
    "slug": "zombie-retros",
    "path": "/2025/july/zombie-retros",
    "date": 1753124861470,
    "status": "public",
    "type": "micropost",
    "tags": [
      "micropost",
      "Teams",
      "Culture"
    ],
    "month": "july",
    "year": 2025,
    "ogImage": "/og-images/zombie-retros.png",
    "blueskyPostUri": "",
    "location": "Boston, MA",
    "lastModified": 1753125409000
  }
]