/* Autogenerated file */
/* do not edit */
import type { HydratedFrontmatter } from "#/types";

export let recentPosts: Array<HydratedFrontmatter> = [
  {
    "title": "On Taste",
    "slug": "on-taste",
    "path": "/2025/august/on-taste",
    "date": 1754250106806,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Random",
      "Thoughts"
    ],
    "description": "_Taste_ is the last key differentiator between those who win and those who lose.",
    "month": "august",
    "year": 2025,
    "ogImage": "/og-images/on-taste.png",
    "blueskyPostUri": "",
    "location": "On a train from Portland, ME to Boston, MA",
    "lastModified": null
  },
  {
    "title": "31",
    "slug": "31",
    "path": "/2025/july/31",
    "date": 1752869036580,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Random",
      "Birthday",
      "Goal",
      "Resolutions"
    ],
    "description": "A quick recap of my goals from the past year and a few goals looking forward as well.",
    "month": "july",
    "year": 2025,
    "ogImage": "/og-images/31.png",
    "blueskyPostUri": "",
    "location": "Boston, MA",
    "lastModified": 1752869812000
  },
  {
    "title": "Roundup Notes in Obsidian with Dataview",
    "slug": "roundup-notes-in-obsidian-with-dataview",
    "path": "/2025/june/roundup-notes-in-obsidian-with-dataview",
    "date": 1750115552955,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Obsidian",
      "Tip",
      "Note Taking",
      "Development"
    ],
    "description": "A quick tip for creating roundup or summary notes based on other notes in Obsidian using the Dataview plugin!",
    "month": "june",
    "year": 2025,
    "ogImage": "/og-images/roundup-notes-in-obsidian-with-dataview.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3lrr4ixwydc2d",
    "location": "",
    "lastModified": 1750380818000
  },
  {
    "title": "Quick Tip - Theme Aware Images",
    "slug": "quick-tip-theme-aware-images",
    "path": "/2025/june/quick-tip-theme-aware-images",
    "date": 1750114295541,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Tip",
      "Web Development",
      "Development"
    ],
    "description": "Have you ever found the need to change the image you render on a web page based on the current preferred color scheme of your theme?",
    "month": "june",
    "year": 2025,
    "ogImage": "/og-images/quick-tip-theme-aware-images.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3lrr37qbdp22d",
    "location": "",
    "lastModified": 1750380818000
  },
  {
    "title": "Async Class Creation In JavaScript",
    "slug": "async-class-creation-in-javascript",
    "path": "/2025/june/async-class-creation-in-javascript",
    "date": 1748981098396,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Web Development",
      "JavaScript",
      "TypeScript",
      "Tip"
    ],
    "description": "Have you ever wanted to create a class in JavaScript or TypeScript but also have the initialization be async? Here's a quick tip on a pattern that I've used in the past!",
    "month": "june",
    "year": 2025,
    "ogImage": "/og-images/async-class-creation-in-javascript.png",
    "location": "",
    "lastModified": 1750380818000
  }
]