/* Autogenerated file */
/* do not edit */
import type { HydratedFrontmatter } from "#/types";

export let recentMicroposts: Array<HydratedFrontmatter> = [
  {
    "title": "Link: What the hell is going on right now?",
    "slug": "link-what-the-hell-is-going-on-right-now",
    "path": "/2025/august/link-what-the-hell-is-going-on-right-now",
    "date": 1755910704752,
    "status": "public",
    "type": "micropost",
    "tags": [
      "micropost",
      "Links"
    ],
    "month": "august",
    "year": 2025,
    "ogImage": "/og-images/link-what-the-hell-is-going-on-right-now.png",
    "blueskyPostUri": "",
    "location": "Boston, MA",
    "lastModified": null
  },
  {
    "title": "Recipe: Horchata Protein Latte",
    "slug": "recipe-horchata-protein-latte",
    "path": "/2025/august/recipe-horchata-protein-latte",
    "date": 1754914452114,
    "status": "public",
    "type": "micropost",
    "tags": [
      "micropost",
      "recipe"
    ],
    "month": "august",
    "year": 2025,
    "ogImage": "/og-images/recipe-horchata-protein-latte.png",
    "blueskyPostUri": "",
    "location": "Boston, MA",
    "lastModified": 1755605056000
  },
  {
    "title": "Zombie Retros",
    "slug": "zombie-retros",
    "path": "/2025/july/zombie-retros",
    "date": 1753124861470,
    "status": "public",
    "type": "micropost",
    "tags": [
      "micropost",
      "Teams",
      "Culture"
    ],
    "month": "july",
    "year": 2025,
    "ogImage": "/og-images/zombie-retros.png",
    "blueskyPostUri": "",
    "location": "Boston, MA",
    "lastModified": 1753125409000
  },
  {
    "title": "Link: How I build software quickly",
    "slug": "link-how-i-build-software-quickly",
    "path": "/2025/july/link-how-i-build-software-quickly",
    "date": 1752491842222,
    "status": "public",
    "type": "micropost",
    "tags": [
      "micropost",
      "Links"
    ],
    "month": "july",
    "year": 2025,
    "ogImage": "/og-images/link-how-i-build-software-quickly.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3ltwbyktpvk24",
    "location": "Boston, MA",
    "lastModified": 1752492696000
  },
  {
    "title": "Vacation (and streaks)",
    "slug": "vacation-and-streaks",
    "path": "/2025/july/vacation-and-streaks",
    "date": 1751898486318,
    "status": "public",
    "type": "micropost",
    "tags": [
      "micropost",
      "Travel"
    ],
    "month": "july",
    "year": 2025,
    "ogImage": "/og-images/vacation-and-streaks.png",
    "blueskyPostUri": "",
    "location": "Gold Beach, Vashon, WA.",
    "lastModified": 1751899155000
  }
]