/* Autogenerated file */
/* do not edit */
import type { HydratedFrontmatter } from "#/types";

export let recentPosts: Array<HydratedFrontmatter> = [
  {
    "title": "Things Leaders Should Never Do",
    "slug": "things-leaders-should-never-do",
    "path": "/2025/november/things-leaders-should-never-do",
    "date": 1764185538935,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Thoughts",
      "Leaders",
      "Teams",
      "Culture",
      "Organizations",
      "Career",
      "Work",
      "Evergreen"
    ],
    "description": "If you're a leader, please never do these things!",
    "month": "november",
    "year": 2025,
    "ogImage": "/og-images/things-leaders-should-never-do.png",
    "blueskyPostUri": "",
    "location": "Stamford, CT",
    "lastModified": 1764186098000
  },
  {
    "title": "In Review - I, Robot",
    "slug": "in-review-i-robot",
    "path": "/2025/september/in-review-i-robot",
    "date": 1759181168550,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Book Review",
      "Books",
      "Thoughts"
    ],
    "description": "I've never read a book that has given me such a visceral reaction as 'I, Robot' has by Isaac Asimov",
    "month": "september",
    "year": 2025,
    "ogImage": "/og-images/in-review-i-robot.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3lzyxwwor5c2r",
    "location": "Boston, MA",
    "lastModified": 1759182020000
  },
  {
    "title": "New GitHub Scams",
    "slug": "new-github-scams",
    "path": "/2025/september/new-github-scams",
    "date": 1758668706993,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "GitHub"
    ],
    "description": "The scammers/spammers on GitHub are getting a bit more creative!",
    "month": "september",
    "year": 2025,
    "ogImage": "/og-images/new-github-scams.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3lzk4qlbqhs2v",
    "location": "Boston, MA",
    "lastModified": 1758673985000
  },
  {
    "title": "In Review - The Nuphy Air75 V3",
    "slug": "in-review-the-nuphy-air75-v3",
    "path": "/2025/september/in-review-the-nuphy-air75-v3",
    "date": 1757519010725,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Product Review",
      "Gear",
      "Keyboard"
    ],
    "description": "I recently changed out my keyboard for daily use from the Nuphy Air75 V2 to the V3 model - and i've had a mixed experience in that change that I figured I should share more broadly.",
    "month": "september",
    "year": 2025,
    "ogImage": "/og-images/in-review-the-nuphy-air75-v3.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3lyimhbhi222s",
    "location": "Boston, MA",
    "lastModified": 1757520414000
  },
  {
    "title": "Build Momentum",
    "slug": "build-momentum",
    "path": "/2025/september/build-momentum",
    "date": 1757362434666,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Random",
      "Opinion",
      "Thoughts"
    ],
    "description": "The trick to successful habits and getting shit done is to just get started and build momentum.",
    "month": "september",
    "year": 2025,
    "ogImage": "/og-images/build-momentum.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3lye36amdb22l",
    "location": "Boston, MA",
    "lastModified": 1757364427000
  }
]