/* Autogenerated file */
/* do not edit */
import type { HydratedFrontmatter } from "#/types";

export let recentSnippets: Array<HydratedFrontmatter> = [
  {
    "title": "Progressive Identifiers",
    "slug": "progressive-identifiers",
    "path": "/2025/september/progressive-identifiers",
    "date": 1758045827940,
    "status": "public",
    "type": "snippet",
    "tags": [
      "snippet",
      "JavaScript",
      "Development"
    ],
    "month": "september",
    "year": 2025,
    "ogImage": "/og-images/progressive-identifiers.png",
    "blueskyPostUri": "",
    "location": "Boston, MA",
    "lastModified": 1758046575000
  },
  {
    "title": "Quick Git",
    "slug": "git-commit-push",
    "path": "/2025/august/git-commit-push",
    "date": 1755911397866,
    "status": "public",
    "type": "snippet",
    "tags": [
      "snippet",
      "Git",
      "Bash"
    ],
    "month": "august",
    "year": 2025,
    "ogImage": "/og-images/git-commit-push.png",
    "blueskyPostUri": "",
    "location": "Boston, MA",
    "lastModified": 1755911760000
  },
  {
    "title": "Multi-step Native HTML Forms",
    "slug": "multi-step-native-html-forms",
    "path": "/2025/july/multi-step-native-html-forms",
    "date": 1751389774207,
    "status": "public",
    "type": "snippet",
    "tags": [
      "snippet",
      "HTML",
      "React"
    ],
    "month": "july",
    "year": 2025,
    "ogImage": "/og-images/multi-step-native-html-forms.png",
    "blueskyPostUri": "",
    "location": "Portland, OR",
    "lastModified": 1751390105000
  },
  {
    "title": "Git Co-Authorship",
    "slug": "git-co-authorship",
    "path": "/2025/june/git-co-authorship",
    "date": 1751343573518,
    "status": "public",
    "type": "snippet",
    "tags": [
      "snippet",
      "Git"
    ],
    "month": "june",
    "year": 2025,
    "ogImage": "/og-images/git-co-authorship.png",
    "blueskyPostUri": "",
    "location": "Portland, OR",
    "lastModified": 1751343614000
  },
  {
    "title": "useInterval",
    "slug": "use-interval",
    "path": "/2025/june/use-interval",
    "date": 1751206166699,
    "status": "public",
    "type": "snippet",
    "tags": [
      "snippet",
      "React"
    ],
    "month": "june",
    "year": 2025,
    "ogImage": "/og-images/use-interval.png",
    "blueskyPostUri": "",
    "location": "Netarts, OR",
    "lastModified": 1751292854000
  }
]