/* Autogenerated file */
/* do not edit */
import type { HydratedFrontmatter } from "#/types";

export let recentPosts: Array<HydratedFrontmatter> = [
  {
    "title": "In Review - The Nuphy Air75 V3",
    "slug": "in-review-the-nuphy-air75-v3",
    "path": "/2025/september/in-review-the-nuphy-air75-v3",
    "date": 1757519010725,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Product Review",
      "Gear",
      "Keyboard"
    ],
    "description": "I recently changed out my keyboard for daily use from the Nuphy Air75 V2 to the V3 model - and i've had a mixed experience in that change that I figured I should share more broadly.",
    "month": "september",
    "year": 2025,
    "ogImage": "/og-images/in-review-the-nuphy-air75-v3.png",
    "blueskyPostUri": "",
    "location": "Boston, MA",
    "lastModified": null
  },
  {
    "title": "Build Momentum",
    "slug": "build-momentum",
    "path": "/2025/september/build-momentum",
    "date": 1757362434666,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Random",
      "Opinion",
      "Thoughts"
    ],
    "description": "The trick to successful habits and getting shit done is to just get started and build momentum.",
    "month": "september",
    "year": 2025,
    "ogImage": "/og-images/build-momentum.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3lye36amdb22l",
    "location": "Boston, MA",
    "lastModified": 1757364427000
  },
  {
    "title": "On Taste",
    "slug": "on-taste",
    "path": "/2025/august/on-taste",
    "date": 1754250106806,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Random",
      "Thoughts"
    ],
    "description": "_Taste_ is the last key differentiator between those who win and those who lose.",
    "month": "august",
    "year": 2025,
    "ogImage": "/og-images/on-taste.png",
    "blueskyPostUri": "",
    "location": "On a train from Portland, ME to Boston, MA",
    "lastModified": 1754250249000
  },
  {
    "title": "31",
    "slug": "31",
    "path": "/2025/july/31",
    "date": 1752869036580,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Random",
      "Birthday",
      "Goal",
      "Resolutions"
    ],
    "description": "A quick recap of my goals from the past year and a few goals looking forward as well.",
    "month": "july",
    "year": 2025,
    "ogImage": "/og-images/31.png",
    "blueskyPostUri": "",
    "location": "Boston, MA",
    "lastModified": 1752869812000
  },
  {
    "title": "Roundup Notes in Obsidian with Dataview",
    "slug": "roundup-notes-in-obsidian-with-dataview",
    "path": "/2025/june/roundup-notes-in-obsidian-with-dataview",
    "date": 1750115552955,
    "status": "public",
    "type": "blog-post",
    "tags": [
      "Obsidian",
      "Tip",
      "Note Taking",
      "Development"
    ],
    "description": "A quick tip for creating roundup or summary notes based on other notes in Obsidian using the Dataview plugin!",
    "month": "june",
    "year": 2025,
    "ogImage": "/og-images/roundup-notes-in-obsidian-with-dataview.png",
    "blueskyPostUri": "https://bsky.app/profile/matthamlin.me/post/3lrr4ixwydc2d",
    "location": "",
    "lastModified": 1750380818000
  }
]